#pragma once
#include <d3d12.h>
#include "ColaMan/Core/RenderCode.h"
D3D12_FILL_MODE GetDX12FillMode(FillMode mode);


D3D12_CULL_MODE GetDX12CullMode(CullMode mode);


D3D12_CONSERVATIVE_RASTERIZATION_MODE GetDX12ConservativeRasterizationMode(CONSERVATIVE_RASTERIZATION_MODE mode);



D3D12_BLEND GetDX12BlendMode(BlendMode mode);



D3D12_BLEND_OP GetDX12BlendOp(BLEND_OP op);

D3D12_LOGIC_OP GetDX12LogicOp(LOGIC_OP op);


D3D12_COLOR_WRITE_ENABLE GetDX12ColorWriteEnable(COLOR_WRITE_ENABLE enable);
D3D12_DEPTH_WRITE_MASK GetDX12DepthWriteMask(DEPTH_WRITE_MASK mask);


D3D12_COMPARISON_FUNC GetDX12ComparisonFunc(COMPARISON_FUNC func);

D3D12_STENCIL_OP GetDX12StencilOp(STENCIL_OP op);

D3D12_PRIMITIVE_TOPOLOGY_TYPE GetDX12PrimitiveTopologyType(PRIMITIVE_TOPOLOGY_TYPE topology);

D3D12_PIPELINE_STATE_FLAGS GetDX12PipelineStateFlags(PIPELINE_STATE_FLAGS flags);



D3D12_ROOT_PARAMETER_TYPE GetDX12RootParameterType(ROOT_PARAMETER_TYPE type);

D3D12_SHADER_VISIBILITY GetDX12ShaderVisibility(SHADER_VISIBILITY visibility);

D3D12_DESCRIPTOR_RANGE_TYPE GetDX12DescriptorRangeType(DESCRIPTOR_RANGE_TYPE rangeType);

D3D12_FILTER GetDX12Filter(FILTER filter);

D3D12_TEXTURE_ADDRESS_MODE GetDX12TextureAddressMode(TEXTURE_ADDRESS_MODE addressMode);

D3D12_STATIC_BORDER_COLOR GetDX12StaticBorderColor(STATIC_BORDER_COLOR borderColor);

D3D12_ROOT_SIGNATURE_FLAGS GetDX12RootSignatureFlags(ROOT_SIGNATURE_FLAGS flags);

uint32_t ShaderDataTypeSize(ShaderDataType type);

DXGI_FORMAT ShaderDataTypeToDX12Type(ShaderDataType shaderType);

DXGI_FORMAT format2DXFormat(ShaderDataType type);

D3D12_DESCRIPTOR_HEAP_TYPE GetDX12DescriptorHeapType(DESCRIPTOR_HEAP_TYPE type);

D3D12_DESCRIPTOR_HEAP_FLAGS GetDX12DescriptorHeapFlag(DESCRIPTOR_HEAP_FLAGS flag);
